apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-deployment-1-dev
spec:
  selector:
    matchLabels:
      app: ml-deployment-1
  replicas: 1
  template:
    metadata:
      labels:
        app: ml-deployment-1
    spec:
      containers:
      - name: ml-deployment-1
        image: fhebal/ml-deployment-1-dev:0.0.1
        env:
        - name: ENVIRONMENT
          value: development
        ports:
        - containerPort: 8080
